plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.azzams.system'
    compileSdk 35

    defaultConfig {
        applicationId 'com.azzams.system'
        minSdk 24
        targetSdk 35
        versionCode 15
        versionName '1.5.0'
    }
}


dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-messaging'
}
